build:
	docker build -t markthebault/k8s-spark-worker:spark2.4.0_haddop3.0.0 .

push:
	docker push markthebault/k8s-spark-worker:spark2.4.0_haddop3.0.0

run:
	docker run -it --rm markthebault/k8s-spark-worker:spark2.4.0_haddop3.0.0
